---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
---

```{r}
source(here::here("R/load.R"))
```


```{r}
wflow_toc <- function(gh_url = "https://jdblischak.github.io", proj_url = "workflowr") {
  root <- file.path(gh_url,proj_url)
  title_regexp <- glue::glue("<title>([\\p{Han}A-z\\.\\s-]+)</title>",
                             .open = '<<',
                             .close = '>>')
  fs::dir_info(here::here("docs"), type = 'file', regexp = '\\.html$') %>%
    dplyr::mutate(
      url = basename(path),
      url = file.path(root,url)
    ) %>%
    dplyr::mutate(
      name = purrr::map(path,~ readr::read_lines(.) %>%
                          stringr::str_subset(title_regexp) %>%
                          stringr::str_match_all(title_regexp)
      )
    ) %>%
    tidyr::unnest() %>%
    dplyr::mutate(
      name = purrr::map_chr(name, ~.[,2])
    ) %>%
    dplyr::select(url, name, dplyr::everything()) %>%
    dplyr::mutate(
      link = glue::glue("1. [{name}]({url})")
    ) %>%
    .$link %>%
    # dplyr::summarise(
    #   value = stringr::str_flatten(link, '\n')
    # ) %>%
    # Error: Column `stringr::str_flatten(link, "\n")` must be length 1 (a summary value), not 0
    # dplyr::pull %>%
    clipr::write_clip()
  message('The table of content of your project is on the clipboard.')

}
```

```{r}
wflow_toc()
```

