---
title: "参数化 RMarkdown 文档"
author: "Jiaxiang Li"
date: "2019-03-19"
output: workflowr::wflow_html
---

[github](https://github.com/jenniferthompson/ParamRmdExample) 是一个 minimal example。
参考 [jla-data](https://www.jla-data.net/eng/parametrized-r-markdown-reports/) 和
[nsaunders](https://nsaunders.wordpress.com/2019/03/04/using-parameters-in-rmarkdown/)
在 yaml 模块，`#`可以作为评论记号，而不执行。

```{r}
library(rmarkdown)
suppressMessages(library(tidyverse))
species_list <- iris$Species %>% unique()
```

```{r}
args(render)
```

未成功。 
 
```{r eval=F}
library(glue)
species_list %>% 
    map(~render(params = list(species = .)),
        input = 'rmd-template.Rmd',
        output_format = 'html_document',
        output_file = glue("{.}.html"),
        output_dir = '../output',
        quiet = T,
        encoding = 'UTF-8'
        )
```

```{r eval=F}
library(rmarkdown)

flowers <- unique(iris$Species) # setosa, versicolor, virginica - you know them all, don't you?

for (i in seq_along(flowers)) {
  myIris <- flowers[i]  # my species - to be reused as 1) parameter & 2) file name
  render("report-template.Rmd", # the template
          params = list(species = myIris), # value of myIris passed to the species parameter
          output_file = paste(myIris, '.pdf', sep = ''), # name of the output file - species name and pdf extension
          quiet = T,
          encoding = 'UTF-8')
```

```
错误: Incomplete expression: 
for (i in seq_along(flowers)) {
  myIris <- flowers[i]  # my species - to be reused as 1) parameter & 2) file name
  render("report-template.Rmd", # the template
          # params = list(species = myIris), # value of myIris passed to the species parameter
          # output_file = paste(myIris, '.pdf', sep = ''), # name of the output file - species name and pdf extension
          # quiet = T,
          encoding = 'UTF-8')
```


参考 [rmarkdown](https://rmarkdown.rstudio.com/lesson-6.html)

```{r eval=F}
render("5-parameters.Rmd", params = list(data = "aleutians"))
```

这样就非常方便

我突然想起来，这就是 DataExplorer 的实现方式。
因此只要 base 在 Rmd 模板进行编写就可以了。 

还可以 knit with params，有UI 这一步没有问题。

## 常见报错

```
Error: params object already exists in knit environment so can't be overwritten by render params
```

参考 [Stack Overflow](https://stackoverflow.com/a/32028424/8625228)
因为 `params` 这个对象该环境中已经有了，我更喜欢这个答案，参考[Stack Overflow](https://stackoverflow.com/a/42104149/8625228)

```{r eval=F}
rmarkdown::render("test.Rmd", params = list(name = "Jordan"), envir = new.env() )
```

```
> source("R/load.R")
> render("jd-template.Rmd",params = list(name = '同学', email = 'example@example.com'),
+        output_format = 'github_document',output_dir = 'test-person'
+        )


processing file: jd-template.Rmd
  |......................                                           |  33%
   inline R code fragments

Quitting from lines 2-86 (jd-template.Rmd) 
Error in nchar(input) : invalid multibyte string, element 1
```

需要设置 `encoding = 'UTF-8'`